# Nome do fluxo de trabalho de automação
name: Deploy to GitHub Pages

# Define quando esta automação deve ser executada
on:
  # Executa em cada push para o branch 'main'
  push:
    branches: ["main"]
  # Permite que você execute este fluxo de trabalho manualmente a partir da aba Actions
  workflow_dispatch:

# Define as permissões necessárias para o deploy
permissions:
  contents: read
  pages: write
  id-token: write

# Define as configurações de concorrência para evitar deploys sobrepostos
concurrency:
  group: "pages"
  cancel-in-progress: true

# Define os trabalhos (jobs) a serem executados
jobs:
  # Trabalho de build
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: 'npm'
      - name: Install dependencies
        run: npm ci --legacy-peer-deps # <-- CORREÇÃO APLICADA AQUI
      - name: Build
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  # Trabalho de deploy
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
